### ISSUE TITLE
Mutations branch: "Can't find variable: require" js error in notebook

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#102]
Installing the "mutations" branch and using the example code in the readme gives a blank page on Jupyter lab. The relevant javascript error seems to be "Can't find variable: require":

<img width="626" alt="Screenshot 2024-11-01 at 09 29 36" src="https://github.com/user-attachments/assets/b8215852-2b7f-4c92-9982-73a7636cc449">

**Comment by kitchensjn** [comment]
Sent you a message on Slack to work through this one!

**Comment by kitchensjn** [comment]
So we have determined that the following JavaScript header is sometimes required at the top of the notebook:

```
%%javascript
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js';
document.head.appendChild(script);
```

Always having this at the top doesn't cause issues, though sometimes it is unnecessary. A note about this is now in the `/docs/tutorial.md`.
