### ISSUE TITLE
Rotating tip labels

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#106]
Is there any way to rotate tip labels by 90 degrees, so that long labels don't clash? A search for "rotate" in the repo didn't produce any obvious clues.

**Comment by kitchensjn** [comment]
Currently not, but I can add that easily this afternoon!

**Comment by kitchensjn** [comment]
Added this to main. `draw(..., rotate_tip_labels=True)` or `draw_node(..., rotate_tip_labels=True)`. Tip labels will be rotated by 90deg. A note when implemented with `draw_node()`, nodes that are "tips" in the subgraph but not in larger graph will not be rotated. Those nodes will have the grey dashed child edge anyways so the label is positioned differently and rotating doesn't make sense that styling. Let me know if that works for you!
