### ISSUE TITLE
y_axis_scale="time" gives blank output for large draw_node() plot

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#110]
In the following plot, if I uncomment `y_axis_scale="time"`, the result is a completely blank cell. The (compressed) JSON is below

![Screenshot 2024-11-27 at 10 47 07](https://github.com/user-attachments/assets/ccc5827e-c822-42af-8679-e6c24a001d96)

[tskit_arg_visualizer.json.bz2.zip](https://github.com/user-attachments/files/17933147/tskit_arg_visualizer.json.bz2.zip)

**Comment by kitchensjn** [comment]
Should be fixed now! Looks like this may have been an issue for a while (since Numpy2 changes) but I hadn't caught it.

**Comment by hyanwong** [comment]
Great. That does indeed work now. Thanks for the fix!
