### ISSUE TITLE
Save mutation's inherited state, not the ancestral state

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#111]
At the moment the mutations dataframe has a column called "ancestral", which I presume is used to fill out the label. This should probably be the "inherited" state of the mutation instead (e.g. if the ancestral_state of the site is `A`, the focal mutation has a derived state of `C`, but there is a mutation at the same site above it on the tree with a derived state of `G`, the mutation should be G->C, not A->C. At the moment this needs to be calculated from the mutation.parent column (but see https://github.com/tskit-dev/tskit/issues/2631 which would make it nicer):

```python
inherited_state = site.ancestral_state if mut.parent == tskit.NULL else ts.mutation(mut.parent).derived_state
```

I suggest that the column be called "inherited" rather than ancestral, to make it clear?

**Comment by kitchensjn** [comment]
I've updated this on the main branch. I had conflated "inherited" and "ancestral". This is really how I had intended it to display, so thanks for catching. I've added an "inherited" column to the mutations data frame that is used to calculate the mutation label. Right now, I've kept the "ancestral" column, though I'm not sure how useful it is

**Comment by hyanwong** [comment]
Just tried this and it works fine. Thanks for the quick fix!
