### ISSUE TITLE
Describe use in a notebook

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#17]
It might be worth adding a few comments about use in a notebook. For instance, the `arg_visualizer.ipynb` example file produces "Javascript Error: require is not defined" in JupytyerLab due to https://stackoverflow.com/questions/66060012/display-d3-js-visualisation-in-jupyter-lab, but it does work nevertheless.

**Comment by kitchensjn** [comment]
Updated the README.md (0562883) to include the proper code block for loading D3 within JupyterLab. Thank you for pointing that out!
