### ISSUE TITLE
Code outputs data (I guess point positions) to screen

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#27]
Currently I'm getting this as the output for a jupyterbook cell (note the vectors that are output before the plot is generated)

<img width="665" alt="Screenshot 2023-08-01 at 12 42 53" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/3da42d5e-dcc9-470d-8771-e2f3bfc297e7">

**Comment by kitchensjn** [comment]
Good catch; an errant print statement that corresponds with children of polytomies. Has been removed!
