### ISSUE TITLE
Placement of leaf labels underneath node

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#29]
I wonder if it would be useful to place the labels for leaf (tip) nodes *under* the node rather than to the top right. This is what we do in the SVG viz.

Here's how it appears currently: nodes with no children have their labels a little obscured by the lines.

<img width="610" alt="Screenshot 2023-08-06 at 19 12 42" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/0f6c792e-cef8-4e7c-b3ab-b9d4f6f794ad">

**Comment by kitchensjn** [comment]
Labels for nodes without children (tips) are now placed underneath the node (81e396f)
