### ISSUE TITLE
Label genome positions (or breaks) on the X axis

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#35]
It might be nice to have an option to show labels for the X axis (presumably the start and end of the genome, and possibly the break positions?)

**Comment by kitchensjn** [comment]
I've added labels to the start and end points of sequence and merged that to main. Having labels at each breakpoint causes the labels to often overlap one another. I think the best solution would be to add a popup that displays the bounds of the region you are hovering over; that way not all labels are shown at once. Reopening this issue until I've implemented the popup feature.

**Comment by kitchensjn** [comment]
Pop up feature is being moved to 0.0.3 milestone. Progress on that will be tracked with #50 rather than here.
