### ISSUE TITLE
Alternative node labels

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#36]
In the SVG code, it is possible to provide a dictionary that maps node IDs to alternative labels for the nodes. I guess this would be relatively easy to implement in the ARG visualiser? The only niggle would be how to cope with the "joint" pair of recombination nodes in a full ARG.

**Comment by kitchensjn** [comment]
Are you thinking that the alternate labels would be specified in a metadata field? The quick solution would be adding an optional parameter to set the label when initializing the D3ARG. But this would means that you would need to create a new D3ARG if you wanted to switch to a different labelling, which seems ugly. Maybe labels should be set each time you call D3ARG.draw()... by default it's ID but you can set it to a metadata field with an optional parameter. There should also be a limit to the length of labels to prevent the whole figure from becoming cluttered. I'll look into this!

P.S. sorry for being slow on the response. I'm in the midst of preparing for my Qualifying Exam so haven't had as much time lately to build out new features with the visualizer.

**Comment by hyanwong** [comment]
No problem on slow response times - thanks for all you have done so far! We haven't encoded labelling using metadata, and in this case, I wanted to show the breakpoints on the recombination nodes, rather than metadata. So I think it would be better to allow arbitrary labels.

I guess one possibility is a separate function/method that you apply to the D3ARG object (e.g. `.setlabels()`), or, as you say, a parameter to the `.draw()` method?

**Comment by kitchensjn** [comment]
Added node label customization - from the README:

### Modifying Node Labels

```
d3arg.set_node_labels(labels={0:"James",6:""})
```

Node labels can be changed using the `set_node_labels()` function. The example above will change the labels of Nodes 0 and 6 to "James" and "", respectively. An empty string is equivalent to removing the label of that specific node. Labels are always converted to strings. You can then redraw `d3arg` with the updated labels. If you wish to go back to the default labelling scheme, you run:

```
d3arg.reset_node_labels()
```
