### ISSUE TITLE
Visualising ARGs inferred from the Kreitman dataset

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#41]
In our ARG paper, we show a number of ARGs inferred from the same classic _D. melanogaster_ dataset (by Kreitman):

<img width="757" alt="Screenshot 2023-09-20 at 17 43 47" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/cd9018d2-d3c8-4a94-bb77-947863a44b33">

It would be great to see how these can be displayed by the ts_arg_visualiser. I've zipped up the respective tree sequences below:

[Kreitman_SNP_inferred_ARGs.zip](https://github.com/kitchensjn/tskit_arg_visualizer/files/12675617/Kreitman_SNP_inferred_ARGs.zip)

**Comment by kitchensjn** [comment]
![KwARG output visualized with tskit_arg_visualizer - time](https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/88201b1f-9000-4d86-9a14-bde12f734c9d)

![KwARG output visualized with tskit_arg_visualizer - rank](https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/0462f233-4349-4545-968d-ef1aa4b76186)

Starting with the simplest one, these are for the ARG from KwARG with `y_axis_scale="time"` and `y_axis_scale="rank"`. For the first, I didn't move the nodes at all. I would say that the ordering of the tips is better in your version. The second one, I've tried to untangle as much as possible. I'm not sure why there are unary nodes (13, 20, 17, 16, etc) in this ARG, but haven't worked with the method before.

**Comment by hyanwong** [comment]
Hmm, perhaps we are creating a 2-RE-node ARG when converting from kwARG, but not setting the flags that you expect. I.e. it may be that 35 & 36 represent a single "recombination node".

**Comment by kitchensjn** [comment]
Wouldn't we then expect nodes 35 and 36 to have the same time? I have node 35 at time=387592 and node 36 at time=144455.

**Comment by hyanwong** [comment]
Good point. Yes we would. I'm not sure why this happens then. I will investigate.

**Comment by hyanwong** [comment]
Ana points out that kwARG doesn't infer times, so these are somewhat arbitrary. The reason that we have 2 re nodes at different times is that to get semi-reasonable times out of the ARG, we run the "tsdate" program on the ARG output from kwARG, and `tsdate` doesn't know to keep the 2 recombination nodes at the same time.

The simplest way around this would be to convert the kwARG output to a 1-RE-node format and keep the mapping of old -> new node IDs. We could then date the 1-re-node version, and port the times back.

This would be useful for redating "full" ARGs from whatever source. The 2-RE-node version is needed to calculate likelihoods under the CwR.

**Comment by hyanwong** [comment]
Apologies - it looks like I only bothered running the tsdate algorithm on my local copy. I have updated the repo placing the correct node flags at https://github.com/tskit-dev/what-is-an-arg-paper/pull/332. A copy of the Kreitman-kwARG inference is below, and it gives a much nicer picture:
[Kreitman_SNP_kwarg.trees.zip](https://github.com/kitchensjn/tskit_arg_visualizer/files/12717150/Kreitman_SNP_kwarg.trees.zip)

<img width="747" alt="Screenshot 2023-09-25 at 21 32 29" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/34d48df3-3142-4357-9f02-f33cab98dd4d">

**Comment by hyanwong** [comment]
This is about the best I can come up with (3 crossings):

<img width="715" alt="Screenshot 2023-10-11 at 09 28 06" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/51059972-a7b4-4ea2-b5c3-f82e84ca4eab">

**Comment by kitchensjn** [comment]
Here's some starting points for visualizations of the different methods: 
[kreitman_jsons.zip](https://github.com/kitchensjn/tskit_arg_visualizer/files/13303364/kreitman_jsons.zip)

The first and last trees from the tsinfer trees appear to be empty in the .trees file that I was using; I don't know if that was intentional or not. Also for most of the them, we are stuck using `edge_type="line"` until I work out the pathing for polytomies. I've added that to the milestone TODO list for v0.0.2. You can almost get away with "ortho" for argweaver, but as the D3ARG object is expecting 2-RE-format when using `D3ARG.from_ts()`, it doesn't quite work.

Let me know if you have trouble running any of the JSONs!

**Comment by hyanwong** [comment]
Thanks. We should have a 2 <-> 1 conversion routine, I guess (difficult for diamonds, though).

The `tsinfer` post-processing step deliberately cuts off the topology before the first site and after the last site, which is why there are empty regions at the start and end of most tsinferred tree sequences.

**Comment by hyanwong** [comment]
I think we are done here
