### ISSUE TITLE
enable different linewidths/colors for edges

### ISSUE THREAD

**Issue by fbaumdicker** [kitchensjn/tskit_arg_visualizer#43]
It would be cool to visualize the relative length of the corresponding sequence intervals for edges by altering the linewidth or the color of the plotted edges. This might depend on #42 .

**Comment by kitchensjn** [comment]
<img width="500" alt="Screenshot 2023-09-21 at 1 57 01 PM" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/a142b626-dc27-452a-9313-6415c515a778">

From this GitHub [branch](https://github.com/kitchensjn/tskit_arg_visualizer/tree/42-mapping-multiple-tskit-edges-with-the-same-parentchild-to-a-single-graph-edge): with D3ARG.draw(variable_edge_width=True), the visualizer scales the stroke width of the edges based on the fraction of sequence that contains the edge. This branch has merged edges as discussed in #42 (except in the cases of "diamonds", where there is a recombination event followed by a coalescent event of the same two lineages). Is this along the lines for what you were thinking?

**Comment by fbaumdicker** [comment]
Awesome @kitchensjn !
This is exactly what I was thinking about. I think this is a great way to quickly visualize the overall importance of edges for the sample. I will have to reschedule some appointments next week to try this feature.
