### ISSUE TITLE
Button to distribute tips evenly

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#48]
I've been playing with the visualiser recently, and it's great. One thing which would be useful would be the ability to take all the nodes of the tree at time 0 (or whatever is the most recent time) and space them out equidistant from each other on the X: i.e. evenly space them.

Quite often, if you are dragging the sample tips around to reorder them, you don't get the spacings exactly even.

I guess this would be somewhat akin to allowing the fixed nodes to move on reheating.

**Comment by kitchensjn** [comment]
It makes sense to add incorporate this functionality into the reheating button, as well as separately. Will look into it!
