### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#54]
I wonder if this project is now mature enough to tag an alpha 0.0.1 release? That might help if we want to use it on the tskit tutorials pages.

**Comment by hyanwong** [comment]
Looks like you are addressing this, thanks @kitchensjn. If you are packaging for PyPI, then there are some relatively simple tskit projects such as https://github.com/tskit-dev/tsdate which have files from which you can copy/paste if you need some examples.

**Comment by kitchensjn** [comment]
Ah, yes! I meant to follow up on this issue. I've been working through a few of the other issues that I think are important to have for the initial release. It should be very close! Thanks for directing me to the tsdate files; very helpful to have an example.

I have my graduate qualifying exam next week, but after that I'll have more time to focus on getting this released.

**Comment by hyanwong** [comment]
Great, no hurry here. Good luck for your exam!

**Comment by kitchensjn** [comment]
Release 0.0.1 is available on GitHub and PyPI. This is my first time releasing a package onto either site, so please let me know if I missed anything obvious or if you have any issues installing and running the visualizer.

**Comment by hyanwong** [comment]
Amazing. Thanks!
