### ISSUE TITLE
Omit unreferenced nodes from plot

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#69]
For teaching purposes, it's helpful to be able to plot ARGs which have been simplified with `keep_unary=True, filter_nodes=False`, so that the node numbers are kept, but unreference nodes (not present in the edge table) are not shown. For example:

```python
import msprime
ts = msprime.sim_ancestry(10, population_size=100, sequence_length=1000, record_full_arg=True, recombination_rate=0.000018, random_seed=1)
smaller_ts = ts.simplify([0,1,2,3,4,5], keep_unary=True, filter_nodes=False)
d3arg = tskit_arg_visualizer.D3ARG.from_ts(smaller_ts)
d3arg.draw(width=600, height=500)  # currently shows all nodes. 
```

**Comment by kitchensjn** [comment]
Now, if you initialize the D3ARG with `ignore_unattached_nodes=True`, the D3ARG will not include attached nodes but remaining nodes maintain the same IDs and labels as before. 

```
d3arg = tskit_arg_visualizer.D3ARG.from_ts(smaller_ts, ignore_unattached_nodes=True)
```

<img alt="tskit_arg_visualizer omit unattached" src="https://github.com/user-attachments/assets/05f2c951-c515-4e65-a18d-f891971a90c8" width="400px">

**Comment by hyanwong** [comment]
Wow, fast work. Thanks a lot!
