### ISSUE TITLE
Docstring needn't say "tree sequence must have marked recombination nodes"

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#71]
The `from_ts` docstring says "tree sequence must have marked recombination nodes", but I think that's only true for the line="ortho" plot.

https://github.com/kitchensjn/tskit_arg_visualizer/blob/e764605ec057a4e3a6eef4f42807ada6b056d19e/tskit_arg_visualizer/__init__.py#L160

Perhaps it should say:

```
ts : tskit.TreeSequence
    If the tree sequencs has marked recombination nodes, such as using
    msprime.sim_ancestry(...,record_full_arg=True), this can be used to
    plot in "ortho" style.
```

**Comment by kitchensjn** [comment]
Thanks for catching that! I agree that the current wording isn't correct, but it may need an extra layer. If flag 131072 isn't ever used in the ARG, everything works as expected for `edge_type="line"`. But the docstring should be more explicit regarding 1-RE versus 2-RE formats as that flag is used to merge recombination nodes. Additionally, there isn't a check to make sure the merging recombination nodes are actually properly paired; it just makes a list of recombination nodes and blindly groups pairs of nodes together. This works for 2-RE format, but in the instance you provide an ARG in 1-RE format with marked recombination nodes (flag 131072, if that ever happens), it will incorrectly try to merge unrelated recombination nodes.
