### ISSUE TITLE
Add genome bar to draw_node()

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#85]
This is, I suspect, a tricky one, but it would be cool to add a bar representing the genome when drawing a subset of nodes using `draw_node()`. This would have to show only the breakpoints present in the displayed subgraph (and presumably would be able to highlight the routes of inheritance through the subgraph too, using mouseover, as in the `draw()` function.

Maybe add this to the "nice to have" pile.

**Comment by kitchensjn** [comment]
<img src="https://github.com/user-attachments/assets/92655c07-d200-46cb-bbbd-724cb763291e" alt="Draw Node With Genome Bar" width="400px">

Here's the concept - The genome bar functions the same as before where edges and blocks are interactive for highlighting. New to this are the gray blocks which are sections of the chromosome that aren't included in the subgraph. These blocks are not interactive. Does this fit with what you were thinking?

**Comment by hyanwong** [comment]
I quite like the grey bars, but for large ARGs (thousands of breakpoints), this might be problematic?

**Comment by kitchensjn** [comment]
I'll add an optional parameter to include the grey or zoom into the included regions.

**Comment by hyanwong** [comment]
I think this is done, so I'm closing it.
