### ISSUE TITLE
Getting the nodes shown in draw_nodes?

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#94]
It can be helpful to get a list of the node ids shown when using the `draw_nodes` function. Do you think this could e.g. be returned by the function itself? If not, is there a way to query the drawing object to get that information out?

**Comment by kitchensjn** [comment]
This commit makes it so that `draw_nodes(..., return_included_nodes=True)` returns a list of node IDs that are included in the subgraph in addition to plotting as usual.

**Comment by hyanwong** [comment]
Nice, thanks!
