### ISSUE TITLE
Static mutation labels not displaying when `include_mutation_labels=True`

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#96]
I assume they are just in the wrong font colour, or the text has been skipped by mistake?

<img width="929" alt="Screenshot 2024-10-14 at 10 25 38" src="https://github.com/user-attachments/assets/fd7b187c-7b0b-4f84-b2e7-411878793b35">

**Comment by hyanwong** [comment]
Not the weird curvy line between nodes 0 and 1, which is usually used to denote one side of a diamond. This might be because node 1 is marked as a sample (it is, indeed, an internal sample).

**Comment by hyanwong** [comment]
In the big ARG, I seem to only have one edge:

```python
>>> for e in ts.edges():
>>>    if e.parent==0 and e.child==1:
>>>         print(e)
Edge(left=0.0, right=29904.0, parent=0, child=1, metadata=b'', id=213254)
```

In the subset graph,

```
>>> len(d3arg.edges[d3arg.edges['alt_parent'] == d3arg.edges['source']])
0
```

**Comment by hyanwong** [comment]
Also, I think you have added in the labels all the time now, even when include_mutation_labels=False:

<img width="849" alt="Screenshot 2024-10-15 at 13 00 04" src="https://github.com/user-attachments/assets/82c5dee1-3714-4664-b653-8f9c9cb9168f">

**Comment by kitchensjn** [comment]
Argh, sorry. Should be fixed now. Thank you for pointing that out.

For the curved edge, could you send me the JSON of the subgraph?

**Comment by hyanwong** [comment]
Thanks for fixing. Here's an example JSON with the curved edge:
[tskit_arg_visualizer.json.zip](https://github.com/user-attachments/files/17385333/tskit_arg_visualizer.json.zip)

**Comment by hyanwong** [comment]
Nice triaging

Alternatively, can you use triple equals: `d.source.id === d.alt_parent`?

**Comment by hyanwong** [comment]
By the way, `condense_mutations=False` seems to do the same as `condense_mutations=True`, and condenses them all the time. I suspect it's a typo slip somewhere.

**Comment by kitchensjn** [comment]
Yep, missed implementing for `draw_node()`. Updated the default to `False` as you suggested in #99 .
