### ISSUE TITLE
Document how to set sample nodes to squares (a la _tskit_)

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#98]
I think this is the fastest method to make large ARGs match the tskit standard styling, where samples are squares. Could we put something like this snippet into the docs somewhere?

```
d3arg.nodes.loc[np.isin(d3arg.nodes["id"], ts.samples()), "symbol"] = 'd3.symbolSquare'
```

**Comment by hyanwong** [comment]
Almost a dupe of https://github.com/kitchensjn/tskit_arg_visualizer/issues/87

**Comment by kitchensjn** [comment]
Added this example to `/docs/tutorial.md`! Thank you.
