### ISSUE TITLE
"Condense mutations" option

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#99]
@szhan suggested an option for mutations whereby you could condense multiple mutations along an edge into a single rectangle on the edge containing the number of mutations, e.g. with a label of `#5`, and when you mouse over the label, a list of mutations pops up (in the same way that a single line pops up when you mouse over the current labels). I guess in this case a set of mutation lines would be shown along the genome bar.

Would this be easy to do @kitchensjn ? I hesitate putting more on your plate, however!

Here's an example of where a list might be more helpful than individual mutations:

![image](https://github.com/user-attachments/assets/b1c1bc73-0188-4338-a273-a446d86f93df)

**Comment by kitchensjn** [comment]
<img width="1083" alt="Screenshot 2024-10-15 at 1 46 33 PM" src="https://github.com/user-attachments/assets/2afdaa50-2834-479f-89c4-24f09367dc78">

Prototype of this. Relatively straightforward to do in Python by generalizing the mutation code that was already there. I won't have much time to build off this later this week but hopefully gives you a start.

**Comment by hyanwong** [comment]
Very cool, thanks a lot.

**Comment by hyanwong** [comment]
Just playing with it. It looks great. Just two suggestions, but no hurry to implement:
* I think it should probably default to `condense_mutations=False`
* I think if `condense_mutations=True, include_mutation_labels=True`, it should show the number of mutations on the edge tick (probably preceded by a hash sign, to distinguish e.g. from the mutation ID). At the moment you have to moss over to see if a condensed mutation block represents just one mutation or lots of them. I guess red isn't such a good colour for showing text on the mutation tick though...

**Comment by hyanwong** [comment]
> maybe a multiplication sign ✖️
Or actually, the N-ARY TIME OPERATOR (⨉) might be more suitable.

**Comment by hyanwong** [comment]
(and by the way, this is *so* useful: thanks for being incredibly responsive!)

**Comment by kitchensjn** [comment]
Added the label for condensed mutations as you suggested. Looks like this one's ready to close, but let me know if there's anything else you'd like with it.
